apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  lb_auth_issuer_uri: http://172.17.97.21:32261
  lb_usuarios_uri: http://172.17.97.21:32473
  port: "8001"
  db_host: mysql:3306
  database: msvc_usuarios
  username: root
  password: root
  cursos_url: msvc-cursos:8002/cursos
  application.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente producción
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
  username: postgres
  password: "123456"
  cursos_url: msvc-usuarios:8001/usuarios
 