apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: mysql:3306
  database: msvc_usuarios
  username: root
  password: root
  cursos_url: msvc-cursos:8002/cursos
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres14:5432
  database: msvc_cursos
  username: postgres
  password: "123456"
  cursos_url: msvc-usuarios:8001/usuarios
 