version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_usuarios
    volumes: 
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14 
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: msvc_cursos
    volumes: 
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
   
  msvc-usuarios:
    container_name: msvc-usuarios
    image: ivanchavarro/usuarios:latest
    #build:
    #  context: ./
    #  dockerfile: ./mcvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./mcvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql
    restart: always
    
  msvc-cursos:
    container_name: msvc-cursos
    #build:
    #  context: ./
    #  dockerfile: ./msvc-cursos/Dockerfile
    image: ivanchavarro/cursos:latest
    ports:
      - "8002:8002"
    env_file:
      - .\msvc-cursos\.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-usuarios
    restart: always
    
volumes: 
  data-mysql:
    name: data-mysql 
  data-postgres:
    name: data-postgres
    
networks: 
   spring:
     name: spring