version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_usuarios
    volumes: 
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: ivanchavarro/usuarios:latest
    #build:
    #  context: ./
    #  dockerfile: ./mcvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment: 
      PORT: 8001
      DB_HOST: mysql:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: root
      CURSOS_URL: http://174.129.92.117:8002/cursos
    networks:
      - spring
    depends_on:
      - mysql
    restart: always
    
volumes: 
  data-mysql:
    name: data-mysql 
    
networks: 
   spring:
     name: spring