apiVersion: v1
kind: PersistentVolume
metadata: 
  name: postgres-pv
spec: #En la documentación de Kubernetes, Concepts, storage, persistent volumes están los atributos permitidos
  capacity:
    storage: 2Gi #Se mide en GB
  volumeMode: Filesystem
  storageClassName: ""
  accessModes: 
  #  - ReadWriteOnce
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b903c266c7c888cb
 # hostPath: 
 #   path: /var/lib/postgresql/data
 #   type: DirectoryOrCreate  