apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306 #puerto del servicio para el tráfico
    protocol: TCP
    targetPort: 3306 #puerto del container
  selector: #Para seleccionar un conjunto de pods que tengan la etiqueta mysql
    app: mysql
  type: ClusterIP
